name: Build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.2.108
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore packages
        run: |
          dotnet restore "./src/Isometric Game.sln"

      - name: Export game
        id: export
        uses: firebelley/godot-export@v4.4.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/mono/Godot_v3.5.1-stable_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/mono/Godot_v3.5.1-stable_mono_export_templates.tpz
          relative_project_path: ./src/
          export_debug: true
          use_preset_export_path: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ steps.export.outputs.build_directory }}/HTML5

      - name: Upload html artifact
        uses: actions/upload-artifact@v3
        with:
          name: html5
          path: ${{ steps.export.outputs.build_directory }}/HTML5

      - name: Upload android artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: ${{ steps.export.outputs.build_directory }}/Android

      - name: Upload windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ${{ steps.export.outputs.build_directory }}/Windows Desktop

      - name: Upload linux x11 artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ${{ steps.export.outputs.build_directory }}/LinuxX11

  deploy:
    needs: build
    name: Deploy to github pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
